# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SwiftAvatar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAvatar

  pod 'Toucan'

  target 'SwiftAvatarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftAvatarUITests' do
    # Pods for testing
  end

end
